### ISSUE TITLE
Setting the same current index, breaks the display. 

### ISSUE THREAD

**Issue by hernangonzalez** [antoninbiret/ABSteppedProgressBar#10]
Hi,

The progress bar will stop rendering if the same value is set at `currentIndex`.

Thanks,
H.

**Comment by antoninbiret** [comment]
I tried to reproduce the issue but I couldn't see any rendering problem. Could you provide a project sample ?

Thanks

**Comment by AlexanderNorway** [comment]
It's super simple to reproduce this error. Just try to set currentIndex where you set all the other properties of ABSteppedProgressBar in your example project. Unlike stated in the above comment, the error is not limited to setting the currentIndex to what it already was. Try any number within the step range.

**Comment by antoninbiret** [comment]
Thanks for the explanation, should be fixed now on the version 0.0.6.
