### ISSUE TITLE
Changing the labels at any time once the sublayers are added

### ISSUE THREAD

**Issue by AlexanderNorway** [antoninbiret/ABSteppedProgressBar#11]
I have a case where I depending on which step the user is on, will need to change the text of the previous step to "V" as in "Done". Any suggestions on how to achieve this without the code becoming very hacky? Also, would be awesome to have both a label inside the circle and a subtitle label underneath the circle.

**Comment by antoninbiret** [comment]
Hi Alexander,

If I understood the question correctly, you will find my way of doing it on the exemple project (more precisely in `ExempleViewController.swift`) on this [branch](/antoninbiret/ABSteppedProgressBar/tree/feature/issue-%2311). It's not really hacky and do the job ;)

For the suggestion, I think this fits only your needs and I don't really want to add complexity for that. However, what we could do is adding a function which gives you the frame (or center position) of each step. With this frame/position you could easily layout your subtitle labels (I made an exemple in this [commit](/antoninbiret/ABSteppedProgressBar/commit/0bbb202d7187350ce3e6e70fb5ea747435a8e98c)). What do you think about it ?

**Comment by aliasbody** [comment]
I have the exact same problem, I mean that just providing the Bullet CGPoint for the current index should be a good start in order for us to handle the presentation of a small label at the top as a subtitle.

**Comment by antoninbiret** [comment]
You should use the branch [feature/issue-#11](/antoninbiret/ABSteppedProgressBar/tree/feature/issue-%2311) for now. I'll create a new version tonight with the center points accessor.

**Comment by aliasbody** [comment]
@antoninbiret Thanks, i'll do that :)
