### ISSUE TITLE
Can you please merge the Swift3 branch?

### ISSUE THREAD

**Issue by slashburn** [antoninbiret/ABSteppedProgressBar#13]
Hi Antonin,

first of all thanks for this great project. It really helped me out.
Can you please merge the swift3 branch into master and create the 0.8 version to support Swift 3?

**Comment by antoninbiret** [comment]
Hi @slashburn, 

Sorry for my late reply, but it's merged now. I still have some issues with travis builds, I'll have a look in the next days.

**Comment by slashburn** [comment]
Thanks for merging, Antonin. You're the man!
