### ISSUE TITLE
Crashing on Swift 4.0 

### ISSUE THREAD

**Issue by humza-ios** [antoninbiret/ABSteppedProgressBar#20]
let attString = NSAttributedString(string: self.string as! String, attributes: attributes as? [String : AnyObject])

File name : ABTextLayerExtension.swift

**Comment by antoninbiret** [comment]
Hi @humza-ios,

Thanks for reporting this issue. On which version did the crash occurred ?
I recently pushed a new version `0.2.0` which is (normally) fully compatible with swift 4.0.

Could you have a try and tell me if you still get a crash ?

**Comment by antoninbiret** [comment]
I assume this issue is fixed with the `0.2.0` release. Feel free to open a new issue if you still have a crash with swift 4.0
