### ISSUE TITLE
Update to Swift 4

### ISSUE THREAD

**Issue by hendyevan** [antoninbiret/ABSteppedProgressBar#21]
Hi, this is a great library for stepped progress bar and i've been using it since swift 3.
And now i update it from version 0.0.8 to version 0.2.0 for support in swift 4.
But after update there is an issue from ABTextLayerExtension.
`let attributes = [NSAttributedStringKey.font: font]`

> Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'<

Can you help me to fix this?
Appreciate your help.

**Comment by antoninbiret** [comment]
Hi @hendyevan, thanks for the bug report. Could you tell me if you have the same issue with the exemple project (which is running with swift 4) ? It seems your configuration is trying to build the library with swift 3.

Could you double check the swift version displayed in the Xcode's build settings of the library's target ?

**Comment by hendyevan** [comment]
Hi @antoninbiret, I have check the swift compiler version and its still using 3.2. After i change to 4 its compiled succesfully. My bad, forgot to change the swift compiler because i thought that it will change automatically. Thanks for your feedback.
