### ISSUE TITLE
Objective c

### ISSUE THREAD

**Issue by milap-eww** [antoninbiret/ABSteppedProgressBar#24]
Is this library compatible with Objective c? Because i am not able to get the delegate methods in objective c Class.

**Comment by antoninbiret** [comment]
Hi @milap-eww. First of all thanks for the bug report. I fixed this issue on #25. Will merge it when green and push a new version.

**Comment by antoninbiret** [comment]
@milap-eww A new version (0.2.1) is available with the fix.
