### ISSUE TITLE
Vertical Progress Bar 

### ISSUE THREAD

**Issue by ghost** [antoninbiret/ABSteppedProgressBar#3]
Thanks for the awesome library. 

Is it possible to have the progress bar in vertical position? I can do it myself if I know where to look. 

Thanks again

**Comment by antoninbiret** [comment]
In the current state of the library, it's impossible to display the progress bar in vertical position and I don't have a lot of time to add this functionality in the next few days/weeks. However, if you plan to do it, don't hesitate to send a PR.

Thanks

**Comment by slashburn** [comment]
Although old, for the others reading this: You could use: [https://github.com/romaHerman/timeLineiOS](https://github.com/romaHerman/timeLineiOS)
