### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by igameram** [antoninbiret/ABSteppedProgressBar#7]
1. An unique ID for the progress bar, when more than one progress bar is added to the screen
2. Ability to set progress  value programmatically

**Comment by hernangonzalez** [comment]
@igameram you can set the value manually with `currentIndex`

**Comment by antoninbiret** [comment]
@igameram 
1. The ProgressBar inherit from `UIView` so you can use the `tag`property to identify the progress bars.
2. As @hernangonzalez said, you can use `currentIndex` to programmatically set the progress value.

**Comment by igameram** [comment]
Thanks @hernangonzalez and @antoninbiret 
1. my bad. I used the currentIndex and the progress bar didnt show up, but later found out it was an issue with my stack view . 
2. I am using the tag 👍 . Thought of checking if any progressID is in plan
