### ISSUE TITLE
[Feature] Custom step Numbers

### ISSUE THREAD

**Issue by hernangonzalez** [antoninbiret/ABSteppedProgressBar#8]
Hi,

Would be great to be able to set different step texts as [A, B, C..], or at least start from 1. Standard users (not programmers) are not that used to see a 0 as the first step.

Thank you,
H.

**Comment by antoninbiret** [comment]
Hi @hernangonzalez,

You already can do it by setting the progress bar's delegate and implement the method : `func progressBar(progressBar: ABSteppedProgressBar,
                            textAtIndex index: Int) -> String`

I agree that I should document it a bit.

**Comment by hernangonzalez** [comment]
I see, @antoninbiret, missed that on the delegate. Thank you.

**Comment by antoninbiret** [comment]
You're welcome
